blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation
    url: https://github.com/OWNER/REPO#readme
    about: Check the documentation for guides and API reference
  - name: 💬 Discussions
    url: https://github.com/OWNER/REPO/discussions
    about: Ask questions and discuss ideas with the community
