name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving this project! Please describe your feature request in detail.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been requested
          required: true
        - label: I have checked the documentation to ensure this feature doesn't exist
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: What other approaches have you thought about?
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: Show how you'd like to use this feature
      placeholder: |
        ```typescript
        // Example usage
        ```
      render: typescript
    validations:
      required: false

  - type: textarea
    id: api
    attributes:
      label: API Design (if applicable)
      description: If this involves new APIs, describe the proposed interface
      placeholder: |
        Proposed function signatures, types, or component props
      render: typescript
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots
      placeholder: Links to similar features in other libraries, mockups, etc.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve my workflow
        - High - Blocking my usage of this library
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
